### ISSUE TITLE
Retain original user program filename

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/staticx#134]
Currently, staticx [adds the user program (being wrapped) to the archive as `.staticx.prog`](https://github.com/JonathonReinhart/staticx/blob/6e2817fcaf8de261d80499f09b3fada526b9cbda/staticx/archive.py#L92).

This causes problems for programs like `busybox` which look at `basename(argv[0])` and change their behavior accordingly. See this example: 
```
$ staticx $(which busybox) busybox.sx
$ ./busybox.sx 
.staticx.prog: applet not found
```

See also #132.

The simple fix for this is to retain the original filename of the user application. At least this way, the application will always see its original name.

However, this doesn't actually allow the staticx-bundled program to have any effect if it is renamed (or symlinked/hardlinked, like with `busybox`). That is more complicated tracked in #133.

**Comment by luis-lavaire** [comment]
Hi.

I'm still having this issue. I did: `staticx /usr/bin/awk awk` (`/usr/bin/awk` is a symlink to `gawk`). Then I ran `./awk` (which, by default, prints the help text) to see if it had worked. This is what I got:

```
Usage: .staticx.prog [POSIX or GNU style options] -f progfile [--] file ...
Usage: .staticx.prog [POSIX or GNU style options] [--] 'program' file ...
...
Examples:
        .staticx.prog '{ sum += $1 }; END { print sum }' file
        .staticx.prog -F: '{ print $1 }' /etc/passwd
```

So the binary is indeed static (`ldd awk`); but, for some reason, `awk` was replaced by `.staticx.prog`.

---

_P.S.: Thanks for working on this project. :)_

**Comment by JonathonReinhart** [comment]
Hi @luis-lavaire, sorry for the confusion.

While #135 (which fixed this issue) has been merged to `master`, I haven't yet published a release of Staticx to [PyPI](https://pypi.org/project/staticx/) with that fix.

If you take a look at the [CHANGELOG](https://github.com/JonathonReinhart/staticx/blob/master/CHANGELOG.md), you'll see this under "Unreleased":

> Bundled applications retain their original name (#135)

However, every merge to `master` gets published to [Test PyPI](https://test.pypi.org/project/staticx/) so you can try out a preview version.

I've confirmed what you saw (with a slight variation) exists in the current latest `0.10.0`:

(Extraneous output excluded)
```
$ /usr/bin/awk --version
GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
```


```
$ virtualenv3 venv-user-prog-filename
$ source ./venv-user-prog-filename/bin/activate
$ pip install staticx
...
Successfully installed pyelftools-0.26 staticx-0.10.0
$ staticx --version
staticx 0.10.0
$ staticx /usr/bin/awk awk.sx


$ ./awk.sx 
Usage: .staticx.prog [POSIX or GNU style options] -f progfile [--] file ...
Usage: .staticx.prog [POSIX or GNU style options] [--] 'program' file ...
...
Examples:
	gawk '{ sum += $1 }; END { print sum }' file
	gawk -F: '{ print $1 }' /etc/passwd
```

But I can confirm that the issue is fixed in the preview release:
```
$ pip install --upgrade -i https://test.pypi.org/simple/ staticx
...
Successfully installed staticx-0.10.0.424
$ staticx --version
staticx 0.10.0.424
$ staticx /usr/bin/awk awk.sx
$ ./awk.sx 
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
...
Examples:
	gawk '{ sum += $1 }; END { print sum }' file
	gawk -F: '{ print $1 }' /etc/passwd
```

(Note that my version of `gawk` on Debian 10 always outputs `gawk` in the Examples, while yours outputs `basename(argv[0])`.)

I plan to officially release `v0.11.0` of Staticx once I get #139 merged, which should happen in the next couple days.

**Comment by luis-lavaire** [comment]
Thanks for the quick response! And thanks for clarifying this to me. I'll be looking forward for `v0.11.0`
