### ISSUE TITLE
Build fails -- ntfw not found

### ISSUE THREAD

**Issue by ChaseGrund** [JonathonReinhart/staticx#14]
ntfw() requires `#define _XOPEN_SOURCE 500` to be declared before including ftw.h, otherwise relevant inclusions are skipped.

Note: fixing this in fork, will submit as pull req. 

Edit:  Possibly only affects GCC (vs using musl )

**Comment by JonathonReinhart** [comment]
Are you seeing this when using GNU libc or Musl?

**Comment by ChaseGrund** [comment]
GCC.  thought I mentioned that in the issue description but apparently not.

**Comment by JonathonReinhart** [comment]
Fixed via PR #16
