### ISSUE TITLE
No module named abc

### ISSUE THREAD

**Issue by rkoornstra** [JonathonReinhart/staticx#165]
Hello,

Upon installing staticx which worked I couldn't run it as it gave the error no module named abc
I tried searching how to install it, but it seems deprecated? 
Staticx version is 0.12.0
Any workaround for this?
Thanks,

Reinoud.

**Comment by JonathonReinhart** [comment]
I need more information, please. What version of Python are you running? Can you please copy+paste the exact command you used to install and the error output?

[`abc`](https://docs.python.org/3/library/abc.html) is part of the standard library for all versions of Python supported by staticx (and beyond).

**Comment by JonathonReinhart** [comment]
I haven't heard back from you so I'm going to close this issue.

For posterity, I think @rkoornstra might be referring to [`collections.abc`](https://docs.python.org/3/library/collections.abc.html) which moved a bunch of things from just `collections`. But this should only be a problem if running on Python < 3.3 which is not supported by StaticX.
