### ISSUE TITLE
libnssfix built incorrectly when build with SCons v4.1.0

### ISSUE THREAD

**Issue by aptalca** [JonathonReinhart/staticx#167]
Hi, I'm using staticx to convert a pyinstaller binary. With pyinstaller 3.5 and on debian (and ubuntu) x86_64, it works fine.

When I try the same exact steps on arm64v8 (also tried arm32v7 with same result), it fails on ldd output of libnssfix.so with the following error:
```
DEBUG:root:Program linked with GLIBC: Found libc.so.6 GLIBC_2.17
DEBUG:root:Running ['patchelf', '--add-needed', 'libnssfix.so', '/tmp/staticx-prog-bxjlmxya']
INFO:root:Adding libnssfix.so
DEBUG:root:Running ['ldd', '/tmp/libnssfix-5mj9jj58.so']
DEBUG:root:Ignoring synthetic library: linux-vdso.so.1
staticx: Unexpected line in ldd output:         lib => not found
```

Here's the full debug log: https://pastebin.com/cYPQa6Uj

I'm building in docker on native hw so all conditions and steps apart from arch are practically the same.

Any ideas?

Thanks

PS. I tried both installing v0.12 from pip as well as build from source with the same result

**Comment by JonathonReinhart** [comment]
I need to make staticx include the full output when ldd fails.

Can you provide that? With `--debug` the temporary files should be left behind (I think... can't look right now).

**Comment by aptalca** [comment]
`--debug` as an argument didn't result in the temporary files to be left behind, however, I was able to find a copy in staticx's folder, which I'm assuming is the one that gets copied to the temp folder during build

```
ldd /usr/local/lib/python3.6/site-packages/staticx/assets/release/libnssfix.so
        linux-vdso.so.1 (0x0000ffff817f8000)
        lib => not found
        libnss_files.so.2 => /lib/aarch64-linux-gnu/libnss_files.so.2 (0x0000ffff8179b000)
        libnss_dns.so.2 => /lib/aarch64-linux-gnu/libnss_dns.so.2 (0x0000ffff81786000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8163c000)
        libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000ffff81617000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff817cd000)
```

**Comment by JonathonReinhart** [comment]
```
        lib => not found
```
Weird. It looks like something went very wrong in the build process. Or there's a bug in `ldd` (glibc)?

Since I only publish binary wheels for x86_64, I'm assuming you installed this from a source distribution (`.tar.gz`).

Can you show me the output of `scons scons_build/release/libnssfix`?

For me:
```
$ scons scons_build/release/libnssfix
scons: Reading SConscript files ...
Checking for NSS...(cached) yes
scons: done reading SConscript files.
scons: Building targets ...
Creating 'scons_build/release/libnssfix/incgen/nsswitch_conf.h'
Creating 'scons_build/release/libnssfix/libc.so.6_stub.c'
gcc -o scons_build/release/libnssfix/libc.so.6_stub.os -c -std=gnu99 -Wall -Werror -Wmissing-prototypes -Wstrict-prototypes -Os -fno-builtin -fPIC -DNDEBUG=1 -DSTATICX_VERSION='"<unknown>"' scons_build/release/libnssfix/libc.so.6_stub.c
gcc -o scons_build/release/libnssfix/libc.so.6 -Wl,-soname=libc.so.6 -nostdlib -shared scons_build/release/libnssfix/libc.so.6_stub.os -Lscons_build/release/lib
gcc -o scons_build/release/libnssfix/nssfix.os -c -std=gnu99 -Wall -Werror -Wmissing-prototypes -Wstrict-prototypes -Os -fPIC -U_FORTIFY_SOURCE -DNDEBUG=1 -DSTATICX_VERSION='"<unknown>"' -Iscons_build/release/libnssfix/incgen libnssfix/nssfix.c
gcc -o scons_build/release/libnssfix/libnssfix.so -Wl,--no-as-needed -nostdlib -Wl,--no-undefined -shared scons_build/release/libnssfix/nssfix.os -Lscons_build/release/lib scons_build/release/libnssfix/libc.so.6 -lnss_files -lnss_dns
scons: done building targets.
```

**Comment by aptalca** [comment]
I tried all, including regular `pip install staticx` and let it build wheels, as well as from tar.gz with `pip install .`

Here's the scons output:
```
scons scons_build/release/libnssfix
scons: Reading SConscript files ...
Checking for NSS...yes
scons: done reading SConscript files.
scons: Building targets ...
Creating 'scons_build/release/libnssfix/incgen/nsswitch_conf.h'
Creating 'scons_build/release/libnssfix/libc.so.6_stub.c'
gcc -o scons_build/release/libnssfix/libc.so.6_stub.os -c -std=gnu99 -Wall -Werror -Wmissing-prototypes -Wstrict-prototypes -Os -fno-builtin -fPIC -DNDEBUG=1 -DSTATICX_VERSION='"<unknown>"' scons_build/release/libnssfix/libc.so.6_stub.c
gcc -o scons_build/release/libnssfix/libc.so.6 -Wl,-soname=lib -nostdlib -shared   scons_build/release/libnssfix/libc.so.6_stub.os $( -Lscons_build/release/lib $) 
gcc -o scons_build/release/libnssfix/nssfix.os -c -std=gnu99 -Wall -Werror -Wmissing-prototypes -Wstrict-prototypes -Os -fPIC -U_FORTIFY_SOURCE -DNDEBUG=1 -DSTATICX_VERSION='"<unknown>"' -Iscons_build/release/libnssfix/incgen libnssfix/nssfix.c
gcc -o scons_build/release/libnssfix/libnssfix.so -Wl,--no-as-needed -nostdlib -Wl,--no-undefined -shared   scons_build/release/libnssfix/nssfix.os $( -Lscons_build/release/lib $) scons_build/release/libnssfix/libc.so.6 -lnss_dns -lnss_files
scons: done building targets.
```

looks like the only difference between yours and mine is on line 8: `-Lscons_build/release/lib` vs `$( -Lscons_build/release/lib $)`

**Comment by JonathonReinhart** [comment]
To be clear, was that build output on `x86_64` or `aarch64`?

Is your `x86_64` build output more like mine, or more like your `aarch64`?

Can you also indicate your version of scons (`scons --version`)?

The differences are a little more than that:
```diff
-gcc -o scons_build/release/libnssfix/libc.so.6 -Wl,-soname=libc.so.6 -nostdlib -shared scons_build/release/libnssfix/libc.so.6_stub.os -Lscons_build/release/lib
+gcc -o scons_build/release/libnssfix/libc.so.6 -Wl,-soname=lib -nostdlib -shared   scons_build/release/libnssfix/libc.so.6_stub.os $( -Lscons_build/release/lib $) 
 gcc -o scons_build/release/libnssfix/nssfix.os -c -std=gnu99 -Wall -Werror -Wmissing-prototypes -Wstrict-prototypes -Os -fPIC -U_FORTIFY_SOURCE -DNDEBUG=1 -DSTATICX_VERSION='"<unknown>"' -Iscons_build/release/libnssfix/incgen libnssfix/nssfix.c
-gcc -o scons_build/release/libnssfix/libnssfix.so -Wl,--no-as-needed -nostdlib -Wl,--no-undefined -shared scons_build/release/libnssfix/nssfix.os -Lscons_build/release/lib scons_build/release/libnssfix/libc.so.6 -lnss_files -lnss_dns
+gcc -o scons_build/release/libnssfix/libnssfix.so -Wl,--no-as-needed -nostdlib -Wl,--no-undefined -shared   scons_build/release/libnssfix/nssfix.os $( -Lscons_build/release/lib $) scons_build/release/libnssfix/libc.so.6 -lnss_dns -lnss_files
```

I think the main problem is the difference in "soname" when building the fake `libnssfix/libc.so.6`:
- Mine: `-Wl,-soname=libc.so.6`
- Yours: `-Wl,-soname=lib`

I don't yet know why that's happening, but that explains why your `libnssfix` is linked against a library named `lib`.

**Comment by JonathonReinhart** [comment]
I'm guessing that [here](https://github.com/JonathonReinhart/staticx/blob/v0.12.0/site_scons/site_tools/stubgen.py#L40), `$_SHLIBSONAME` is not being fully expanded in your version of SCons for some reason. Only `SHLIBSUFFIX` (`lib`) is ending up in the result.

You can try this quick patch:
```diff
diff --git a/site_scons/site_tools/stubgen.py b/site_scons/site_tools/stubgen.py
index 2cc5921..b516c71 100644
--- a/site_scons/site_tools/stubgen.py
+++ b/site_scons/site_tools/stubgen.py
@@ -37,7 +37,7 @@ def ShlibStubGen(env, target, symbols):
             '-fno-builtin',
         ],
         LINKFLAGS = env['LINKFLAGS'] + [
-            '-Wl,-soname=$_SHLIBSONAME',
+            '-Wl,-soname=${TARGET.name}',
             '-nostdlib',
         ],
         SHLIBSUFFIX='',
```

**Comment by aptalca** [comment]
Yes, that was the aarch64 output.

scons version:
```
scons --version
SCons by Steven Knight et al.:
        SCons: v4.1.0.post1.dc58c175da659d6c0bb3e049ba56fb42e77546cd, 2021-01-20 04:32:28, by bdbaddog on ProDog2020
        SCons path: ['/usr/local/lib/python3.6/site-packages/SCons']
Copyright (c) 2001 - 2021 The SCons Foundation
```
With that patch of stubgen.py, libnssfix.so seems to be correctly generated:
```
ldd /usr/local/lib/python3.6/site-packages/staticx/assets/release/libnssfix.so
        linux-vdso.so.1 (0x0000ffff86321000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8619a000)
        libnss_dns.so.2 => /lib/aarch64-linux-gnu/libnss_dns.so.2 (0x0000ffff86185000)
        libnss_files.so.2 => /lib/aarch64-linux-gnu/libnss_files.so.2 (0x0000ffff86165000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff862f6000)
        libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000ffff86140000)
```
With that, staticx finished without errors: https://pastebin.com/8jUheCRJ

Although, my binary didn't work, but that's probably a different issue so I'll open a new github issue for that.
The error when running it is:
```
/dist/docker-compose --version
[49354] Cannot open self /tmp/staticx-bGS9W1/docker-compose or archive /tmp/staticx-bGS9W1/docker-compose.pkg
```

**Comment by aptalca** [comment]
I did some more testing and can confirm that installing v0.12 from source on both x86_64 and aarch64 results in the error from the original post. Installing with pip on x86_64 works fine (likely because the pre-built wheel is used and not locally built).

Applying the patch to stubgen.py fixes the issue when building locally on both x86_64 and aarch64.

The issue with my binary from the last post appears to be a pyinstaller issue (pyinstaller also doesn't work when locally built, but works on x86_64 with pre-built wheel), but that's beyond the scope of this project.

Thanks

**Comment by JonathonReinhart** [comment]
I confirmed that this is a change in behavior of SCons somewhere between v3.0.1 (as packaged in Debian Buster) and v4.1.0.post1.

- v3.0.1 :heavy_check_mark:
- v4.1.0.post1 :x:
- v3.1.2 :heavy_check_mark: 
- v4.0.0 :heavy_check_mark: 
- v4.0.1 :heavy_check_mark: 
- v4.1.0 :x:
