### ISSUE TITLE
PyInstalled applications fail with "Cannot open self"

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/staticx#170]
First reported here: https://github.com/JonathonReinhart/staticx/issues/167#issuecomment-773790859

I also see this in CI jobs:
https://travis-ci.org/github/JonathonReinhart/staticx/jobs/757788708

This is definitely a recent issue with a new version of PyInstaller, because staticx master was passing but now fails: https://travis-ci.org/github/JonathonReinhart/staticx/builds/757790293

**Comment by JonathonReinhart** [comment]
[This build job](https://travis-ci.org/github/JonathonReinhart/staticx/jobs/731410286) for `master` (e91a9054 2020-09-29) passed w/ pyinstaller-4.0.

[This build job](https://travis-ci.org/github/JonathonReinhart/staticx/jobs/757790296) for `master` (same commit, e91a9054 2021-02-06) failed w/ pyinstaller-4.2.

That narrows it down a lot.

**Comment by JonathonReinhart** [comment]
Debug:

```
$ PYINSTALLER="python3 $(realpath ~/gitrepos/pyinstaller/pyinstaller.py) --debug bootloader" test/pyinstall/run_test.sh
...
Running staticx executable
[18646] PyInstaller Bootloader 3.x
[18646] LOADER: executable is /tmp/staticx-zepJSf/app
[18646] LOADER: homepath is /tmp/staticx-zepJSf
[18646] LOADER: _MEIPASS2 is NULL
[18646] LOADER: archivename is /tmp/staticx-zepJSf/app
[18646] Loader: Cannot find cookie[18646] LOADER: archivename is /tmp/staticx-zepJSf/app.pkg
[18646] LOADER: Cannot open archive: /tmp/staticx-zepJSf/app.pkg
[18646] Cannot open self /tmp/staticx-zepJSf/app or archive /tmp/staticx-zepJSf/app.pkg
```

**Comment by aptalca** [comment]
We've been hitting this issue with any pyinstaller version compiled locally. We can provide some more test results, but in a nutshell:
pyinstaller 3.5 and 3.6 --> works on x86_64 with prebuilt wheels, but fails when built locally
pyinstaller >=4.1 --> fails with or without prebuilt wheels
(I don't think I tested 4.0 specifically)

By fail, I mean that when the binary is put through staticx, it produces the error `Cannot open self . . .`

**Comment by JonathonReinhart** [comment]
@aptalca Yep, that's exactly what I was seeing too. I was starting to debug the bootloader but I didn't get very far. I did confirm that the embedded user app does indeed still have the `MEI...` "cookie" at the same location in the `pyidata` section, so I'm not yet sure why it's failing, but I'm sure GDB will tell me when I get back to it.

**Comment by danihodovic** [comment]
Works with py3.9.1, pyinstaller 4.0.

Fails with py3.9.1, pyinstaller 4.2.

**Comment by erwan-mas-okcupid** [comment]
i had this problem 

with python 3.5 ( debian strech ) 
works with pyinstaller 4.0 does not work with pyinstaller 4.1 , pyinstaller 4.2

with python 3.7 ( debian buster ) 
works with pyinstaller 4.0 does not work with pyinstaller 4.1 , pyinstaller 4.2 , but works pyinstaller 4.3 , pyinstaller 4.4

so if you are using 3.5 you must use pyinstaller 4.0 
so if you are using 3.7 you must use pyinstaller 4.0 or 4.3 or 4.4 

pyinstaller drop compatiblity with python 3.5 starting version 4.3 

I dont know if you can  detect if the binary was build with pyinstaller and wich version . So you can generate a error if you  try to statify a exe build with version 4.1 and 4.2

**Comment by ErwanMAS** [comment]
i had this problem

with python 3.5 ( debian strech )
works with pyinstaller 4.0 does not work with pyinstaller 4.1 , pyinstaller 4.2

with python 3.7 ( debian buster )
works with pyinstaller 4.0 does not work with pyinstaller 4.1 , pyinstaller 4.2 , but works pyinstaller 4.3 , pyinstaller 4.4

so if you are using 3.5 you must use pyinstaller 4.0
so if you are using 3.7 you must use pyinstaller 4.0 or 4.3 or 4.4

pyinstaller drop compatiblity with python 3.5 starting version 4.3

I dont know if you can detect if the binary was build with pyinstaller and wich version . So you can generate a error if you try to statify a exe build with version 4.1 and 4.2
