### ISSUE TITLE
Recursively handle symlinks

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/staticx#2]
I'm not sure if it can happen (based on the way ldd works), but handle (or at least recognize) the case where there is more than one symlink in the resolution of a library path. We need to create all intermediate symlinks.

**Comment by ChaseGrund** [comment]
Added code to api.py in my fork to resolve this issue.  

Note, the original code actually incorrectly added symlink files to the archive -- the links could point to the original file path.  The new code corrects that issue as well.

**Comment by JonathonReinhart** [comment]
Implemented in #18
