### ISSUE TITLE
undefined symbol: forkpty, version GLIBC_2.2.5

### ISSUE THREAD

**Issue by jimparis** [JonathonReinhart/staticx#231]
I have a staticx binary I built a while back.  My notes on how I built it were:

```
sudo apt install python3.9 scons libacl1-dev libfuse-dev libpython3.9-dev patchelf
git clone https://github.com/borgbackup/borg.git
cd borg
virtualenv --python=python3.9 borg-env
source borg-env/bin/activate
pip install -r requirements.d/development.txt
pip install pyinstaller
pip install llfuse
pip install -e .[llfuse]
pyinstaller --clean --noconfirm scripts/borg.exe.spec
pip install staticx
staticx -l /lib/x86_64-linux-gnu/libm.so.6 dist/borg.exe borg.x86_64
```

When I had glibc 2.33 installed on the host system, it runs fine.  **After upgrading the host to glibc 2.34**, I get:

```
$ ./borg.x86_64
[3580343] Error loading Python lib '/home/jim/tmp/_MEIHkMaBP/libpython3.9.so.1.0': dlopen: /home/jim/tmp/_MEIHkMaBP/libpython3.9.so.1.0: undefined symbol: forkpty, version GLIBC_2.2.5
```

One thing I notice is that running the binary appears to use the system libutil:

```
$ strace -f ./borg.x86_64 2>&1 | grep /lib/x86
[pid 3580407] openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libutil.so.1", O_RDONLY|O_CLOEXEC) = 3
$
```

and I also noticed that glibc 2.34 appears to have [changed libutil to be empty](https://lwn.net/Articles/864920/)

I don't understand all the black magic at play here.  Was the original binary built incorrectly?

Here is the binary for reference [borg.x86_64.zip](https://github.com/JonathonReinhart/staticx/files/9590707/borg.x86_64.zip)

**Comment by JonathonReinhart** [comment]
Hi @jimparis,

Staticx binaries *should be* totally independent of the LIBC on the system on which they are executed. That said, there have been a number of issues fixed where this independence was not guaranteed.

I recommend you rebuild the binary using the latest version of Staticx. If you have any doubts, you can follow the steps in the [troubleshooting guide](https://staticx.readthedocs.io/en/latest/troubleshooting.html). And of course please feel free to ask any questions or report any successes here!

**Comment by jimparis** [comment]
Previous binary was built with staticx 0.13.3 (I think).  I rebuilt it with 0.13.8 and it no longer opens `libutil.so.1`, so yeah, it appears fixed (Or building against the newer glibc helped somehow).  Thanks!  I did notice that it still opens up one glibc-related file, but maybe this doesn't matter:
```
$ strace -f ./borg.x86_64 2>&1 | grep /lib/x86
[pid 3587259] openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 3
$
```
