### ISSUE TITLE
run staticx on shared libraries

### ISSUE THREAD

**Issue by francesco-ballarin** [JonathonReinhart/staticx#234]
Dear staticx team,
over at https://github.com/fem-on-colab/fem-on-colab I have a complex workflow that is currently broken due to https://github.com/googlecolab/colabtools/issues/3397

The summary of the issue is that, in order to use a much newer compiler than the one available on a cloud platform, I have to compile my libraries with `-static-libstdc++`, and rely on the cloud maintainers to export the old `libstdc++.so` in `LD_PRELOAD` for my libraries to work. This has been the case for years, but in a backward-incompatible change the cloud maintainers have now unset `LD_PRELOAD`. Without that, many of the generated libraries will encounter subtle issues.

While looking for possible workarounds, I stumbled upon this project, and I would like to inquire as follows:
1. can I use staticx on shared libraries, rather than executables? I can't touch the executables  (python, jupyter) shipped by the cloud provider, what I would like to do is enforce the equivalent of `LD_PRELOAD=system libstdc++.so` in my own shared libraries
2. if so, would it be possible/wise to use staticx with the goal of  enforce `LD_PRELOAD=system libstdc++.so`, or do you expect there will be issues? The concern here is that `libstdc++` is not just like *any* library I compile on my own, especially in my use case where I basically want to mix up two different versions of `libstdc++`.
3. if so, is there any way I can statically add just `system libstdc++.so`, rather than all shared libraries? The goal would be to add just the one bit that is causing the issue, while I can continue shipping the remaining libraries as I have been doing for the past two years.

If there are alternative projects that might be better suited for my goal I'd be happy to get alternate suggestions!

Thanks!
Francesco

**Comment by ruanformigoni** [comment]
Hi there, I have a project that uses `staticx` which creates portable containers, I think that may possibly help you if I understood correctly. Would this resolve your issue with outdated cloud compilers?

```c++
# This uses the latest gcc contained inside 'arch.arts' to compiled the project in the current dir.
./arch.arts arts-exec cmake ... 
# This creates a binary that is statically linked with the resources from inside the 'arch.arts' container.
./arch.arts arts-exec apt install -y python3-pip
./arch.arts arts-root pip3 install staticx
./arch.arts arts-exec ./build/my-binary ./my-binary-static
```

**Comment by francesco-ballarin** [comment]
Thanks @ruanformigoni , I'll have a look if I can use arts in my case. I have found another workaround in the meantime, so either way (sticking with my workaround, or using arts), this issue can be closed.
