### ISSUE TITLE
Staticx cannot use pyinstaller 5.10.0

### ISSUE THREAD

**Issue by erikbosch** [JonathonReinhart/staticx#235]
I detected an issue when pyinstaller was updated from 5.9.0 to 5.10.0. It is not considered to be a regression in pyinstaller. I do not know how easy it would be to refactor staticx, or if the short term solution is to just set a dependency that pyinstaller must be =< 5.9.0

https://github.com/pyinstaller/pyinstaller/issues/7560

**Comment by JonathonReinhart** [comment]
Staticx uses a PyInstaller internal API that is subject to change without warning, so this is on Staticx to detect and fix.

Staticx will need to either detect the version of PyInstaller or inspect the objects returned by their APIs and use them appropriately.

I don't have bandwidth for this right now, but I'd be happy to review a PR.

**Comment by JonathonReinhart** [comment]
Fixed in [staticx v0.13.9](https://github.com/JonathonReinhart/staticx/releases/tag/v0.13.9) (#236, #237).

Thanks @andrewthetechie for the initial fix!
