### ISSUE TITLE
ASan runtime does not come first in initial library list

### ISSUE THREAD

**Issue by bcapt** [JonathonReinhart/staticx#263]
Hi,
I've got a binary that requires libasan.so library that has to come first. This is an error I am getting when trying to run static binary after it is converted by the staticx tool:

```
==12345==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```

I am wondering if there's a way to fix this other than recompiling the binary without the `-fsanitize=address` option.

**Comment by JonathonReinhart** [comment]
We might be able to work around this, but I have to ask: why are you packaging asan-enabled binaries for distribution? Normally asan binaries are used for debug testing, but you wouldn't ship them, since they can be significantly larger and slower than a release build.

**Comment by bcapt** [comment]
Oh, in such case, Let me simply try to re-compile my binary without it. Sorry for being ignorant on the fact that this is usually used in a non-release build.
