### ISSUE TITLE
Wrong license and missing ficense files

### ISSUE THREAD

**Issue by htgoebel** [JonathonReinhart/staticx#37]
Since this program is using PyInstaller, it is to be licensed under the GPL. Please fix the license and add the appropriate license files as required by the GPL.

**Comment by JonathonReinhart** [comment]
Will do!
For the record, I specifically requested this feedback in pyinstaller/pyinstaller#2645.

**Comment by JonathonReinhart** [comment]
Done in 2e381bd1cb90f393e9f8f10010fbfc0e9dca4191.

**Comment by htgoebel** [comment]
Thanks :-)
