### ISSUE TITLE
Error with ldd issuing "statically linked"

### ISSUE THREAD

**Issue by ole-de** [JonathonReinhart/staticx#67]
1st of all: great stuff. Thanks a lot!

When I run staticx on a pyinstaller wrapped app, it stops with

staticx: Unexpected line in ldd output:   statically linked

It occurs with running ldd on

_json.cpython-36m-x86_64-linux-gnu.so

This actually *is* dynamically linked but seems to not rely on any .so:

objdump -p _json.cpython-36m-x86_64-linux-gnu.so | fgrep NEEDED

gives *nothing*. So, looks ldd only assumes it is not a shared lib.

Anyway, working around this should be possible with a small patch to elf.py:

```
     for line in output.splitlines():
+        if re.search ("statically linked", line):
+            continue
         m = pat.match(line)
         if not m:
             raise ToolError('ldd', "Unexpected line in ldd output: " + line)
```

Thanks, Ole

**Comment by JonathonReinhart** [comment]
Hi Ole, thanks for the bug report!

Can you help me reproduce this issue locally by answering a few questions?
- What OS and version are you running?
- What version of Python (I'm assuming 3.6) and how did you install it?
- Do you have a minimal example of an application that would show this behavior?

I'm trying to understand why `ldd` would ever say `statically linked` for a `.so` file.

**Comment by ole-de** [comment]
Hi Jonathon,

sure. I couldn't believe it either. I am using a Docker container for running PyInstaller. That uses ubuntu:18.04. I am attaching the Dockerfile. The problem does NOT occur on my host system (Gentoo).

Steps to reproduce:

```
cd dir-where-you-put-the-attachments
docker build --rm -t pyinstaller-linux .
docker run --rm -v "`pwd`:/src" pyinstaller-linux "pyinstaller test.py && chown -R --reference . dist __pycache__ build test.spec"
ldd dist/test/_json.cpython-36m-x86_64-linux-gnu.so
```

Cheers, Ole

[test.zip](https://github.com/JonathonReinhart/staticx/files/2572931/test.zip)

**Comment by JonathonReinhart** [comment]
Ole, your analysis is absolutely correct. 

Regarding `_json.cpython-36m-x86_64-linux-gnu.so`:
- The one from Ubuntu 18.04 has no `DT_NEEDED` tags
- The one from Fedora 28 is linked against `libpython`, `libpthrad`, and `libc`, as expected
- [`_json.zip`](https://github.com/JonathonReinhart/staticx/files/2576471/_json.zip)

```
$ readelf -d _json.cpython-36m-x86_64-linux-gnu.fedora28.so 

Dynamic section at offset 0x11bc0 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.6m.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x1ca0
 0x000000000000000d (FINI)               0xf8ec
 0x0000000000000019 (INIT_ARRAY)         0x211ba8
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x211bb0
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x228
 0x0000000000000005 (STRTAB)             0x970
 0x0000000000000006 (SYMTAB)             0x268
 0x000000000000000a (STRSZ)              1324 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x211dc0
 0x0000000000000002 (PLTRELSZ)           1272 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x17a8
 0x0000000000000007 (RELA)               0xf68
 0x0000000000000008 (RELASZ)             2112 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x0000000000000018 (BIND_NOW)           
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0xf38
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0xe9c
 0x000000006ffffff9 (RELACOUNT)          72
 0x0000000000000000 (NULL)               0x0

$ readelf -d _json.cpython-36m-x86_64-linux-gnu.ubuntu1804.so 

Dynamic section at offset 0x11e00 contains 20 entries:
  Tag        Type                         Name/Value
 0x000000000000000c (INIT)               0x1b18
 0x000000000000000d (FINI)               0xfaa8
 0x0000000000000019 (INIT_ARRAY)         0x211df0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x211df8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x938
 0x0000000000000006 (SYMTAB)             0x248
 0x000000000000000a (STRSZ)              1238 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x212000
 0x0000000000000002 (PLTRELSZ)           1224 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x1650
 0x0000000000000007 (RELA)               0xe10
 0x0000000000000008 (RELASZ)             2112 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          72
 0x0000000000000000 (NULL)               0x0
```

And in this case, [`rtld` will print "statically linked"](https://github.com/bminor/glibc/blob/glibc-2.27/elf/rtld.c#L1891):
```
$ LD_TRACE_LOADED_OBJECTS=1 /lib64/ld-linux-x86-64.so.2 ./_json.cpython-36m-x86_64-linux-gnu.ubuntu1804.so
	statically linked
```

So there must be something strange about the way that those modules are built.

Regardless, I think your patch is correct. `statically linked` here means that the shared object has no dependencies, but it is still a valid shared object, and thus we should include it.

**Comment by JonathonReinhart** [comment]
Try out #70.

**Comment by ole-de** [comment]
My native Gentoo _json.cpython-36m-x86_64-linux-gnu.so also has the three expected references. Unfortunately I failed to run pyinstaller successfully with my project on this box...

```
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.6m.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

Oh, btw - yeah your fix works fine.

One more (stupid and OT) question: how do I refer to exactly the version holding this patch when I use pip3 to install staticx? Do you have some version number?

Thanks, Ole

**Comment by JonathonReinhart** [comment]
> How do I refer to exactly the version holding this patch when I use pip3 to install staticx?

First, note that the Pull Request (#70) says:

> **JonathonReinhart** wants to merge 1 commit into `master` from `67-statically-linked-so`

So `67-statically-linked-so` is the name of the branch that has my patch.

From there, you can use this:

```
$ pip install git+https://github.com/JonathonReinhart/staticx.git@67-statically-linked-so
```

Source: https://stackoverflow.com/a/13754517/119527

**Comment by ole-de** [comment]
Hmm, I was rather hoping for an "official release" version number to refer to with pip.

Anyway, thanks a lot!

**Comment by JonathonReinhart** [comment]
Ah. Check out [`VERSIONING.md`](https://github.com/JonathonReinhart/staticx/blob/master/VERSIONING.md).

Essentially:
- Feature/bugfix branches do not get published
- `master` gets published to Test PyPI: https://test.pypi.org/project/staticx/
- Tags get published to PyPI: https://pypi.org/project/staticx/

**Comment by ole-de** [comment]
Got it working to my liking. For everybody interested in this:

```
pip3 install --extra-index-url https://test.pypi.org/simple staticx==0.5.0.160
```

Version number may of course need adjustment.

**Comment by JonathonReinhart** [comment]
Note: that works because #70 was merged to `master`. If it hadn't, then it wouldn't be on PyPI anywhere.

I've just tagged [`v0.6.0`](https://github.com/JonathonReinhart/staticx/releases/tag/v0.6.0), so it should be available on [PyPI](https://pypi.org/project/staticx/) shortly.
