### ISSUE TITLE
Error when pyinstaller archive holds .so in subdirs

### ISSUE THREAD

**Issue by ole-de** [JonathonReinhart/staticx#68]
I encountered an exception with "no such file or directory" when trying to process a pyinstaller archive which has .so files in subdirs like this:

lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so

The following patch to pyinstaller.py should fix this:

```
             # Extract it to a temporary location
             x, data = pyi_ar.extract(n)
             tmppath = os.path.join(tmpdir, name)
             logging.debug("Extracting to {}".format(tmppath))
+            dirname = os.path.dirname(tmppath)
+            if not os.path.exists(dirname):
+                os.makedirs(dirname)
             with open(tmppath, 'wb') as f:
                 f.write(data)
```

This ensures, the path is existing where the temp file is created.

Thanks, Ole

**Comment by JonathonReinhart** [comment]
@ole-de Could you try out [`68-pyinstaller-subdirs`](https://github.com/JonathonReinhart/staticx/tree/68-pyinstaller-subdirs) and confirm that it fixes your issue?

**Comment by ole-de** [comment]
Yes, this works fine for me. Thanks, Ole
