### ISSUE TITLE
Error loading Python lib '/tmp/staticx-xxxxxx/libpython2.7.so.1.0': dlopen: /tmp/staticx-xxxxxx/libpython2.7.so.1.0

### ISSUE THREAD

**Issue by Mogztter** [JonathonReinhart/staticx#76]
Hello,

I'm trying to build a statically linked binary of https://github.com/blockdiag/blockdiag

So far I've been able to produce a binary with PyInstaller:

```
$ ldd blockdiag
	linux-vdso.so.1 (0x00007ffe0d3eb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f825602d000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8255e10000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8255a1f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8256231000)
```
```
$ ./blockdiag --help
Usage: blockdiag [options] infile

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -a, --antialias       Pass diagram image to anti-alias filter
  -c FILE, --config=FILE
                        read configurations from FILE
  --debug               Enable debug mode
  -o FILE               write diagram to FILE
  -f FONT, --font=FONT  use FONT to draw diagram
  --fontmap=FONT        use FONTMAP file to draw diagram
  --no-transparency     do not make transparent background of diagram (PNG
                        only)
  --size=SIZE           Size of diagram (ex. 320x240)
  -T TYPE               Output diagram as TYPE format
  --nodoctype           Do not output doctype definition tags (SVG only)
  -s, --separate        Separate diagram images for each group (SVG only)
```

As suggested in https://github.com/pyinstaller/pyinstaller/wiki/FAQ#gnulinux I'm using Staticx to produce a statically linked binary:
```
$ staticx blockdiag blockdiag-staticx
```
```
$ ldd blockdiag-staticx
    not a dynamic executable
```

So far so good, but when I run this binary the following error is thrown:

```
$ ./blockdiag-staticx
[3286] Error loading Python lib '/tmp/staticx-gonChC/libpython2.7.so.1.0': dlopen: /tmp/staticx-gonChC/libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

I can't tell if I did something wrong or if it's a bug... ?
Maybe I should try with Python 3 ?
Any help would be greatly appreciated :wink: 

Thanks

#### Version

```
$ python --version
Python 2.7.15rc1
$ pip --version
pip 19.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
$ staticx --version
staticx 0.6.0
$ pyinstaller --version
3.4
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Comment by Mogztter** [comment]
I think I found the solution, I need to manually add library with the `-l` argument.
Now it's working but the binary is very slow to start:

```
$ time ./blockdiag-staticx --version
.staticx.prog 1.5.4
./blockdiag-staticx --version  2,03s user 0,10s system 99% cpu 2,127 total
```
```
$  ./blockdiag --version
blockdiag 1.5.4
./blockdiag --version  0,08s user 0,01s system 99% cpu 0,095 total
```

As you can see the staticx version took 2.03 seconds but the original binary took 0.08seconds.
Maybe I've added too much libraries, I will dig further.

**Comment by Mogztter** [comment]
With less libraries it's a bit faster:

```
$ time ./dist/blockdiag-staticx --version
.staticx.prog 1.5.4
./dist/blockdiag-staticx --version  0,63s user 0,05s system 99% cpu 0,678 total
```

**Comment by JonathonReinhart** [comment]
@Mogztter Thanks for the bug report. Sorry this took a while to respond. I tried on and off to figure out what was going on, but I think it's a simple problem.

I suspect you built your pyinstalled application in the default `--onedir` mode, and not in `--onefile` mode. If you build a "one-folder" bundle, and then move the resulting application out of that directory, it will emit the same error. This isn't really any fault of staticx; it's just the way that PyInstaller works in the default mode.

Instead, pass `--onefile` or `-F` to `pyinstaller`. Then instead of finding a directory under `dist/` you'll find a single executable. This should then be able to be handled by staticx.

Please let me know if this resolves your problem. If so, I'll try to add a note or FAQ to staticx that explains this. There's not really much I can do in staticx to even detect this misuse, because the executable in the "one-folder" directory is statically-linked, and uses `dlopen()` to open `libpython.so`.

**Comment by Mogztter** [comment]
Hello Jonathon and thanks for your reply.
I will give it a try and let you know how it goes 👍

**Comment by JohnnyVM** [comment]
> @Mogztter Thanks for the bug report. Sorry this took a while to respond. I tried on and off to figure out what was going on, but I think it's a simple problem.
> 
> I suspect you built your pyinstalled application in the default `--onedir` mode, and not in `--onefile` mode. If you build a "one-folder" bundle, and then move the resulting application out of that directory, it will emit the same error. This isn't really any fault of staticx; it's just the way that PyInstaller works in the default mode.
> 
> Instead, pass `--onefile` or `-F` to `pyinstaller`. Then instead of finding a directory under `dist/` you'll find a single executable. This should then be able to be handled by staticx.
> 
> Please let me know if this resolves your problem. If so, I'll try to add a note or FAQ to staticx that explains this. There's not really much I can do in staticx to even detect this misuse, because the executable in the "one-folder" directory is statically-linked, and uses `dlopen()` to open `libpython.so`.

Hi, i have the same problem and tried your solution:
`pyinstaller --onefile linux.spec`

```bash
# staticx --loglevel DEBUG manager static
DEBUG:root:Running ['patchelf', '--set-interpreter', 'iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii', '--set-rpath', 'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr', '--force-rpath', '/tmp/staticx-prog-pje12n8o']
INFO:root:Program interpreter: /lib64/ld-linux-x86-64.so.2
INFO:root:Using XZ BCJ filter FILTER_X86
INFO:root:Adding /tmp/staticx-prog-pje12n8o as .staticx.prog
DEBUG:root:Running ['ldd', 'manager']
DEBUG:root:Ignoring synthetic library: linux-vdso.so.1
INFO:root:    Adding Symlink libdl.so.2 => libdl-2.15.so
INFO:root:    Adding /lib/x86_64-linux-gnu/libdl-2.15.so as libdl-2.15.so
INFO:root:    Adding Symlink libz.so.1 => libz.so.1.2.3.4
INFO:root:    Adding /lib/x86_64-linux-gnu/libz.so.1.2.3.4 as libz.so.1.2.3.4
INFO:root:    Adding Symlink libc.so.6 => libc-2.15.so
INFO:root:    Adding /lib/x86_64-linux-gnu/libc-2.15.so as libc-2.15.so
INFO:root:    Adding Symlink ld-linux-x86-64.so.2 => ld-2.15.so
INFO:root:    Adding /lib/x86_64-linux-gnu/ld-2.15.so as ld-2.15.so
INFO:root:Opened PyInstaller archive!
DEBUG:root:Running ['objcopy', '--add-section', '.staticx.archive=/tmp/staticx-archive-f8ipmdee.tar', '/tmp/staticx-output-e826qpbm']
```

and get the same error:
```bash
# ./static
[1935] Error loading Python lib '/tmp/staticx-FDkgdn/libpython3.8.so.1.0': dlopen: /tmp/staticx-FDkgdn/libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by JonathonReinhart** [comment]
Since I haven't heard back from you, I'm closing this issue. If you have more information, please feel free to comment.

**Comment by Mogztter** [comment]
Sorry I didn't reply sooner!
I can confirm that I get the same error when I pass `--onefile` or `-F` to `pyinstaller`:

```
$  ./build/blockdiag/blockdiag
[11037] Error loading Python lib '/path/to/blockdiag/build/blockdiag/libpython2.7.so.1.0': dlopen: /path/to/blockdiag/build/blockdiag/libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

> Please let me know if this resolves your problem. If so, I'll try to add a note or FAQ to staticx that explains this. There's not really much I can do in staticx to even detect this misuse, because the executable in the "one-folder" directory is statically-linked, and uses dlopen() to open libpython.so.

This does not really solve my problem since the binary (produced by `pyinstaller`) relies on `dlopen` to open `libpython.so`.
So you're saying that manually adding missing libraries with the `-l` argument is the way to go right?

```
$ time ./dist/blockdiag-staticx --version
.staticx.prog 1.5.4
./dist/blockdiag-staticx --version  0,63s user 0,06s system 99% cpu 0,692 total
```

But why the binary is 7-10 times slower to start? Is there something I can do to make it faster?

Thanks!
