### ISSUE TITLE
App can't detect it's own path

### ISSUE THREAD

**Issue by jay0lee** [JonathonReinhart/staticx#80]
https://pythonhosted.org/PyInstaller/runtime-information.html

PyInstaller has above docs on detecting path of the onefile executable (the script at the bottom of page is useful for testing). However, this doesn't seem to work for StaticX binaries:
- sys.executable (which frozen scripts should use) gives the /tmp/staticx-NNNN directory.
- os.path.realpath(__file__) gives the current working directory.

How can a StaticX binary detect it's own path?

**Comment by JonathonReinhart** [comment]
This is related to #5. The staticx bootloader should set a couple environment variables:
- The tempdir path where binaries are extracted
- The path of the original staticx binary

**Comment by jay0lee** [comment]
Thanks for the info. As a temp workaround I'm renaming the staticx binary to -staticx and then creating a simple batch file:

    #!/usr/bin/env bash

    mypath=$(realpath $0)
    export MY_REAL_PATH=$(dirname $mypath)
    staticx_binary="$mypath-staticx"
    "$staticx_binary" "$@"

then my Python script can do os.environ.get('MY_REAL_PATH') to determine it's true path.

**Comment by JonathonReinhart** [comment]
@jay0lee Check out #81 -- I added an environment variable, `STATICX_PROG_PATH`, which communicates the absolute path of the staticx binary to the program being wrapped. I'll wait to merge that until I confirm that this provides what you're looking for. Let me know if you need help trying out that branch.

**Comment by jay0lee** [comment]
Compiled with this PR and it seems to work great for detecting StaticX and getting the path of the StaticX executable. Thanks!
