### ISSUE TITLE
staticx broken for aarch64?

### ISSUE THREAD

**Issue by chaoflow** [JonathonReinhart/staticx#93]
We're using staticx (current master: 2dc7ce2d92c27cbdfca3c4a2f2467049582a4bf9) in conjunction with pyinstaller to generate single binary files on x86_64 and aarch64. On x86_64 everything works as expected, on aarch64 however we get:

```
[2542] Cannot open self /tmp/staticx-RQatmS/.staticx.prog or archive /tmp/staticx-RQatmS/.staticx.prog.pkg
```

Full build log can be found here: https://gitlab.com/ApexAI/ade-cli/-/jobs/264761544.

Any hints are greatly appreciated.

**Comment by chaoflow** [comment]
Here is a link to the failing binary: https://gitlab.com/ApexAI/ade-cli/-/jobs/264795793/artifacts/file/dist/ade+aarch64

**Comment by chaoflow** [comment]
The problem was with pyinstaller. See https://github.com/pyinstaller/pyinstaller/pull/4450 by @durko above.

**Comment by JonathonReinhart** [comment]
Thanks for following up; I haven't had any time to look into this.

While I agree PyInstaller should use the ELF sections to locate its data, it'd be better if `patchelf` (via `staticx`) didn't have to reorder any ELF sections and effectively break PyInstaller.
